from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[4]
HARNESS_SCRIPT_ROOT = REPO_ROOT / ".codex" / "harness" / "scripts"
if str(HARNESS_SCRIPT_ROOT) not in sys.path:
    sys.path.insert(0, str(HARNESS_SCRIPT_ROOT))

import materialize_task_workspace as materialize_module
from harness_utils import (
    HARNESS_ROOT,
    METADATA_CANDIDATE_NAMES,
    RUN_ROOT,
    SPEC_ROOT,
    TRANSCRIPT_CANDIDATE_NAMES,
    WORKSPACE_ARTIFACT_NAMES,
    WORKSPACE_ROOT,
    configure_utf8_stdio,
    infer_completed_stages,
    load_json,
    validate_with_named_schema,
    write_json,
)


configure_utf8_stdio()

PLACEHOLDER_NOTE = "Generated by om-session-acceptance. Replace placeholders with real task evidence before export or acceptance."
STAGE_ARTIFACT_HINTS = {
    "ADMISSION": ("admission_result",),
    "DISCOVERY": ("intake_brief",),
    "RESEARCH": ("research_brief",),
    "DESIGN": ("design_packet",),
    "DESIGN_CRITIQUE": ("critique_report", "gate_result"),
    "VERIFY": ("verification_report",),
    "DELIVER": ("delivery_report",),
}


@dataclass
class PreflightReport:
    source_root: Path
    source_mode: str
    transcript_path: Path | None
    metadata_path: Path | None
    manifest_path: Path | None
    artifact_paths: dict[str, Path]
    bundle_name: str | None
    current_state: str | None
    completed_stages: list[str]
    eval_id: str | None
    user_approval_granted: bool
    user_approval_evidence: str
    missing_items: list[str]
    invalid_items: list[str]
    duplicate_artifacts: list[str]
    recommended_action: str
    can_execute_directly: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Preflight and execute the OM session acceptance workflow.")
    parser.add_argument("--source-root", type=Path, required=True, help="Source directory: loose materials, workspace, or bundle.")
    parser.add_argument("--mode", choices=("preflight", "execute"), default="preflight", help="Preflight only or run the pipeline.")
    parser.add_argument("--workspace-name", help="Workspace name. Defaults to source name, or <source>-scaffold for workspace scaffolds.")
    parser.add_argument("--workspace-root", type=Path, default=WORKSPACE_ROOT, help="Workspace output root.")
    parser.add_argument("--bundle-root", type=Path, default=RUN_ROOT, help="Bundle output root.")
    parser.add_argument("--eval-id", help="Eval id override.")
    parser.add_argument("--scaffold-missing", action="store_true", help="Generate a minimal workspace skeleton when inputs are incomplete.")
    parser.add_argument("--validate", action="store_true", help="Run acceptance after export, or directly for bundle input.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite generated workspace or bundle output when it exists.")
    parser.add_argument("--dry-run", action="store_true", help="Print planned actions without writing files or invoking downstream scripts.")
    return parser.parse_args()


def find_candidate_file(source_root: Path, candidate_names: tuple[str, ...]) -> Path | None:
    for name in candidate_names:
        direct_path = source_root / name
        if direct_path.exists():
            return direct_path.resolve()

    for path in sorted(source_root.rglob("*")):
        if path.is_file() and path.name in candidate_names:
            return path.resolve()
    return None


def collect_artifact_paths(source_root: Path, source_mode: str) -> tuple[dict[str, Path], list[str]]:
    artifact_paths: dict[str, Path] = {}
    duplicates: list[str] = []

    search_paths: list[Path]
    if source_mode in {"bundle", "workspace"}:
        artifact_root = source_root / "artifacts"
        search_paths = sorted(artifact_root.glob("*.json")) if artifact_root.is_dir() else []
    else:
        search_paths = sorted(source_root.rglob("*.json"))

    for path in search_paths:
        if path.name in {"manifest.json", *METADATA_CANDIDATE_NAMES}:
            continue
        if path.stem not in WORKSPACE_ARTIFACT_NAMES:
            continue
        resolved_path = path.resolve()
        if path.stem in artifact_paths and artifact_paths[path.stem] != resolved_path:
            duplicates.append(f"{path.stem}: {artifact_paths[path.stem]} | {resolved_path}")
            continue
        artifact_paths[path.stem] = resolved_path

    return artifact_paths, duplicates


def safe_load_json(path: Path) -> tuple[Any | None, str | None]:
    try:
        return load_json(path), None
    except json.JSONDecodeError as exc:
        return None, f"{path.name}: invalid JSON ({exc.msg})"
    except OSError as exc:
        return None, f"{path.name}: read failed ({exc})"


def validate_json_file(artifact_name: str, path: Path) -> tuple[Any | None, list[str]]:
    data, load_error = safe_load_json(path)
    if load_error:
        return None, [load_error]

    errors = validate_with_named_schema(artifact_name, data)
    if errors:
        return data, [f"{path.name}: {'; '.join(errors)}"]
    return data, []


def build_preflight_report(args: argparse.Namespace) -> PreflightReport:
    source_root = args.source_root.resolve()
    source_mode = materialize_module.detect_source_mode(source_root)
    transcript_path = find_candidate_file(source_root, TRANSCRIPT_CANDIDATE_NAMES)
    metadata_path = find_candidate_file(source_root, METADATA_CANDIDATE_NAMES) if source_mode != "bundle" else None
    manifest_path = (source_root / "manifest.json").resolve() if (source_root / "manifest.json").exists() else None
    artifact_paths, duplicate_artifacts = collect_artifact_paths(source_root, source_mode)

    invalid_items: list[str] = []
    metadata_data: dict[str, Any] = {}
    if metadata_path:
        loaded_metadata, metadata_errors = validate_json_file("metadata", metadata_path)
        if metadata_errors:
            invalid_items.extend(metadata_errors)
        if isinstance(loaded_metadata, dict):
            metadata_data = loaded_metadata

    manifest_data: dict[str, Any] = {}
    if manifest_path:
        loaded_manifest, manifest_errors = validate_json_file("manifest", manifest_path)
        if manifest_errors:
            invalid_items.extend(manifest_errors)
        if isinstance(loaded_manifest, dict):
            manifest_data = loaded_manifest

    artifact_data: dict[str, Any] = {}
    for artifact_name, artifact_path in artifact_paths.items():
        loaded_artifact, artifact_errors = validate_json_file(artifact_name, artifact_path)
        if artifact_errors:
            invalid_items.extend(artifact_errors)
        if loaded_artifact is not None:
            artifact_data[artifact_name] = loaded_artifact

    current_state = None
    workflow_state = artifact_data.get("workflow_state")
    if isinstance(workflow_state, dict):
        raw_state = workflow_state.get("current_state")
        if isinstance(raw_state, str):
            current_state = raw_state

    design_packet = artifact_data.get("design_packet")
    eval_id = args.eval_id or manifest_data.get("eval_id") or metadata_data.get("eval_id")
    bundle_name = manifest_data.get("bundle_name") or metadata_data.get("bundle_name")
    user_approval_granted = bool(
        metadata_data.get("user_approval_granted")
        if "user_approval_granted" in metadata_data
        else manifest_data.get("user_approval_granted")
        if "user_approval_granted" in manifest_data
        else isinstance(design_packet, dict) and design_packet.get("approval_status") == "approved"
    )
    user_approval_evidence = str(
        metadata_data.get("user_approval_evidence")
        or manifest_data.get("user_approval_evidence")
        or ""
    )
    completed_stages = (
        metadata_data.get("completed_stages")
        or manifest_data.get("completed_stages")
        or infer_completed_stages(set(artifact_paths.keys()), current_state, user_approval_granted)
    )

    missing_items: list[str] = []
    if transcript_path is None:
        missing_items.append("transcript markdown file")
    if source_mode == "bundle" and manifest_path is None:
        missing_items.append("manifest.json")
    if not artifact_paths:
        missing_items.append("recognized artifact json file")
    if duplicate_artifacts:
        missing_items.append("duplicate artifact names")
    if eval_id is None:
        missing_items.append("eval id (--eval-id or metadata/manifest field)")

    spec_path = SPEC_ROOT / f"{eval_id}.json" if eval_id else None
    needs_spec = source_mode == "bundle" or args.validate
    if needs_spec and (spec_path is None or not spec_path.exists()):
        missing_items.append(f"eval spec for {eval_id or '<missing-eval-id>'}")

    can_execute_directly = not missing_items and not invalid_items

    if can_execute_directly:
        if source_mode == "bundle":
            recommended_action = "Run acceptance directly against the existing bundle."
        elif source_mode == "workspace":
            recommended_action = "Export a bundle from the existing workspace and optionally validate it."
        else:
            recommended_action = "Materialize a workspace from loose materials, export a bundle, and optionally validate it."
    elif args.scaffold_missing:
        recommended_action = "Generate a minimal workspace scaffold and stop for manual completion."
    else:
        recommended_action = "Fill the blocking gaps or rerun with --scaffold-missing."

    return PreflightReport(
        source_root=source_root,
        source_mode=source_mode,
        transcript_path=transcript_path,
        metadata_path=metadata_path,
        manifest_path=manifest_path,
        artifact_paths=artifact_paths,
        bundle_name=bundle_name,
        current_state=current_state,
        completed_stages=completed_stages,
        eval_id=eval_id,
        user_approval_granted=user_approval_granted,
        user_approval_evidence=user_approval_evidence,
        missing_items=missing_items,
        invalid_items=invalid_items,
        duplicate_artifacts=duplicate_artifacts,
        recommended_action=recommended_action,
        can_execute_directly=can_execute_directly,
    )


def default_workspace_name(report: PreflightReport, args: argparse.Namespace) -> str:
    if args.workspace_name:
        return args.workspace_name
    if report.source_mode == "workspace":
        return f"{report.source_root.name}-scaffold"
    return report.source_root.name


def planned_workspace_root(report: PreflightReport, args: argparse.Namespace) -> Path:
    return args.workspace_root.resolve() / default_workspace_name(report, args)


def planned_bundle_root(report: PreflightReport, args: argparse.Namespace) -> Path:
    if report.bundle_name:
        bundle_name = report.bundle_name
    elif report.source_mode == "materials":
        bundle_name = default_workspace_name(report, args)
    else:
        bundle_name = report.source_root.name
    return args.bundle_root.resolve() / bundle_name


def build_command_plan(report: PreflightReport, args: argparse.Namespace) -> list[list[str]]:
    commands: list[list[str]] = []

    if report.source_mode == "bundle":
        spec_path = SPEC_ROOT / f"{report.eval_id}.json"
        commands.append(
            [
                sys.executable,
                str(HARNESS_ROOT / "scripts" / "run_session_acceptance.py"),
                "--bundle",
                str(report.source_root),
                "--spec",
                str(spec_path),
            ]
        )
        return commands

    if report.source_mode == "materials":
        materialize_command = [
            sys.executable,
            str(HARNESS_ROOT / "scripts" / "materialize_task_workspace.py"),
            "--source-root",
            str(report.source_root),
            "--workspace-name",
            default_workspace_name(report, args),
            "--output-root",
            str(args.workspace_root.resolve()),
        ]
        if report.eval_id:
            materialize_command.extend(["--eval-id", report.eval_id])
        if args.overwrite:
            materialize_command.append("--overwrite")
        commands.append(materialize_command)

    exporter_task_root = report.source_root if report.source_mode == "workspace" else planned_workspace_root(report, args)
    export_command = [
        sys.executable,
        str(HARNESS_ROOT / "scripts" / "export_session_bundle.py"),
        "--task-root",
        str(exporter_task_root),
        "--output-root",
        str(args.bundle_root.resolve()),
    ]
    if report.eval_id:
        export_command.extend(["--eval-id", report.eval_id])
    if args.overwrite:
        export_command.append("--overwrite")
    if args.validate:
        export_command.append("--validate")
    commands.append(export_command)
    return commands


def format_command(command: list[str]) -> str:
    return subprocess.list2cmdline(command)


def print_preflight(report: PreflightReport, args: argparse.Namespace) -> None:
    print("== OM Session Acceptance Preflight ==", flush=True)
    print(f"Source root: {report.source_root}", flush=True)
    print(f"Source mode: {report.source_mode}", flush=True)
    print(f"Transcript: {report.transcript_path if report.transcript_path else 'missing'}", flush=True)
    print(f"Metadata: {report.metadata_path if report.metadata_path else 'not found'}", flush=True)
    print(f"Manifest: {report.manifest_path if report.manifest_path else 'not found'}", flush=True)
    print(f"Eval id: {report.eval_id or 'missing'}", flush=True)
    print(f"Current state: {report.current_state or 'unknown'}", flush=True)
    print(f"Completed stages: {', '.join(report.completed_stages) if report.completed_stages else 'none'}", flush=True)
    print(f"User approval granted: {report.user_approval_granted}", flush=True)

    if report.artifact_paths:
        print("Artifacts:", flush=True)
        for artifact_name, artifact_path in sorted(report.artifact_paths.items()):
            print(f"  - {artifact_name}: {artifact_path}", flush=True)
    else:
        print("Artifacts: none", flush=True)

    if report.missing_items:
        print("Blocking gaps:", flush=True)
        for item in report.missing_items:
            print(f"  - {item}", flush=True)
    else:
        print("Blocking gaps: none", flush=True)

    if report.invalid_items:
        print("Invalid items:", flush=True)
        for item in report.invalid_items:
            print(f"  - {item}", flush=True)
    else:
        print("Invalid items: none", flush=True)

    if report.duplicate_artifacts:
        print("Duplicate artifacts:", flush=True)
        for item in report.duplicate_artifacts:
            print(f"  - {item}", flush=True)

    print(f"Recommended action: {report.recommended_action}", flush=True)

    if report.source_mode != "bundle":
        print(f"Planned workspace root: {planned_workspace_root(report, args)}", flush=True)
        print(f"Planned bundle root: {planned_bundle_root(report, args)}", flush=True)

    command_plan = build_command_plan(report, args) if report.can_execute_directly else []
    if command_plan:
        print("Planned commands:", flush=True)
        for command in command_plan:
            print(f"  - {format_command(command)}", flush=True)


def run_command_plan(command_plan: list[list[str]]) -> int:
    for command in command_plan:
        print(f"> {format_command(command)}", flush=True)
        result = subprocess.run(command, check=False)
        if result.returncode != 0:
            return result.returncode
    return 0


def build_metadata_for_scaffold(report: PreflightReport) -> dict[str, Any]:
    notes = [PLACEHOLDER_NOTE]
    notes.extend(f"Missing input: {item}" for item in report.missing_items)
    notes.extend(f"Invalid input: {item}" for item in report.invalid_items)
    notes.extend(f"Duplicate artifact: {item}" for item in report.duplicate_artifacts)

    metadata: dict[str, Any] = {
        "task_id": report.source_root.name,
        "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "source_mode": report.source_mode,
        "source_root": str(report.source_root),
        "completed_stages": report.completed_stages,
        "user_approval_granted": report.user_approval_granted,
        "notes": notes,
    }
    if report.eval_id:
        metadata["eval_id"] = report.eval_id
    if report.bundle_name:
        metadata["bundle_name"] = report.bundle_name
    if report.user_approval_evidence:
        metadata["user_approval_evidence"] = report.user_approval_evidence
    return metadata


def placeholder_artifact_names(report: PreflightReport) -> list[str]:
    names_to_create: set[str] = set()
    for stage in report.completed_stages:
        for artifact_name in STAGE_ARTIFACT_HINTS.get(stage, ()):
            if artifact_name not in report.artifact_paths:
                names_to_create.add(artifact_name)
    if report.completed_stages and "workflow_state" not in report.artifact_paths:
        names_to_create.add("workflow_state")
    return [name for name in sorted(names_to_create) if name in WORKSPACE_ARTIFACT_NAMES]


def scaffold_placeholder_payload(artifact_name: str, report: PreflightReport) -> dict[str, Any]:
    return {
        "_template": f"Replace this placeholder with a valid {artifact_name} artifact before export or acceptance.",
        "_source_root": str(report.source_root),
        "_current_state": report.current_state or "unknown",
    }


def scaffold_workspace(report: PreflightReport, args: argparse.Namespace) -> Path:
    workspace_root = planned_workspace_root(report, args)
    if workspace_root.exists():
        if not args.overwrite:
            raise FileExistsError(f"workspace already exists: {workspace_root}. Use --overwrite to replace it.")
        shutil.rmtree(workspace_root)

    (workspace_root / "artifacts").mkdir(parents=True, exist_ok=True)
    metadata = build_metadata_for_scaffold(report)
    write_json(workspace_root / "metadata.json", metadata)

    if report.transcript_path:
        shutil.copy2(report.transcript_path, workspace_root / "transcript.md")
    else:
        transcript_placeholder = "\n".join(
            [
                "# TODO: Replace Transcript Placeholder",
                "",
                PLACEHOLDER_NOTE,
                f"- Source root: {report.source_root}",
                "- Copy key conversation excerpts into this file before export or acceptance.",
                "",
            ]
        )
        (workspace_root / "transcript.md").write_text(transcript_placeholder, encoding="utf-8")

    for artifact_name, artifact_path in sorted(report.artifact_paths.items()):
        shutil.copy2(artifact_path, workspace_root / "artifacts" / f"{artifact_name}.json")

    for artifact_name in placeholder_artifact_names(report):
        placeholder_path = workspace_root / "artifacts" / f"{artifact_name}.json"
        if placeholder_path.exists():
            continue
        write_json(placeholder_path, scaffold_placeholder_payload(artifact_name, report))

    return workspace_root


def main() -> int:
    args = parse_args()
    report = build_preflight_report(args)
    print_preflight(report, args)

    if args.mode == "preflight":
        return 0 if report.can_execute_directly else 1

    if args.dry_run:
        if report.can_execute_directly:
            return 0
        if args.scaffold_missing:
            print(f"Dry run: would scaffold workspace at {planned_workspace_root(report, args)}", flush=True)
            return 0
        return 1

    if report.can_execute_directly:
        return run_command_plan(build_command_plan(report, args))

    if args.scaffold_missing:
        workspace_root = scaffold_workspace(report, args)
        print(f"Generated workspace scaffold: {workspace_root}", flush=True)
        print("Scaffold generation stops here. Replace placeholder files before export or acceptance.", flush=True)
        return 1

    print("Execution stopped because the input set is incomplete or invalid.", flush=True)
    print("Rerun with --scaffold-missing after confirming the files to be created.", flush=True)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
